defaults:
    run:
        working-directory: ./frontend

name: ESLint and Prettier CI
on:
    push:
jobs:
    frontend-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checks out the latest Git commit
              uses: actions/checkout@v2
            - name: Sets up a Node.js environment
              uses: actions/setup-node@v2
            - run: npm ci
            - run: npx eslint --ext .js --max-warnings 0 .
            - run: npx prettier --config .prettierrc.json -l "*.{js,json,vue}"
